version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_gram
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  app:
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - POSTGRES_URL=host=postgres user=root password=root port=5432 dbname=my_gram sslmode=disable
      - PORT=5000
      - JWT_KEY=TDR3000
      - APP_NAME=app
    volumes:
      - ./:/app
  
volumes:
  postgres_db: